### ISSUE TITLE
Error on catkin_make, can't find OculusSDK 0.3

### ISSUE THREAD

**Issue by fredinhuf** [ros-visualization/oculus_rviz_plugins#18]
I am trying to to put it to work with DK2 too, and I have OculusSDK 0.3 on my home folder, but I get the following error:

```
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - oculus_rviz_plugins
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'oculus_rviz_plugins'
-- ==> add_subdirectory(oculus_rviz_plugins)
CMake Error at oculus_rviz_plugins/CMakeLists.txt:17 (FIND_PACKAGE):
  Could not find module FindOculusSDK.cmake or a configuration file for
  package OculusSDK.

  Adjust CMAKE_MODULE_PATH to find FindOculusSDK.cmake or set OculusSDK_DIR
  to the directory containing a CMake configuration file for OculusSDK.  The
  file will have one of the following names:

    OculusSDKConfig.cmake
    oculussdk-config.cmake



CMake Error at /opt/ros/groovy/share/catkin/cmake/catkin_package.cmake:156 (message):
  catkin_package() DEPENDS on 'OculusSDK' which must be find_package()-ed
  before.  If it is a catkin package it can be declared as CATKIN_DEPENDS
  instead without find_package()-ing it.
Call Stack (most recent call first):
  /opt/ros/groovy/share/catkin/cmake/catkin_package.cmake:98 (_catkin_package)
  oculus_rviz_plugins/CMakeLists.txt:23 (catkin_package)


-- Configuring incomplete, errors occurred!
Invoking "cmake" failed
```

**Comment by wjwwood** [comment]
I'm not sure what versions of the OculusSDK are supported, but it looks like it cannot find the OculusSDK cmake file. Maybe @dgossow can comment on this if he has time, but I'm not sure if the root cause of this problem is a configuration error or a change in the OculusSDK.

**Comment by fredinhuf** [comment]
Yeah, 0.3 is not the expected version of the SDK to use with this plugin, I am trying to put it to work with sdk 0.3, but, anyway, I tried with the correct version of the SDK:
cloned https://github.com/ros-visualization/oculus_sdk into home/fred/OculusSDK, and then make, no errors.
then, tried to catkin_make my catkin_ws that contains oculus_rviz_plugins and the same appears:

CMake Error at oculus_rviz_plugins/CMakeLists.txt:17 (FIND_PACKAGE):
  Could not find module FindOculusSDK.cmake or a configuration file for
  package OculusSDK.

  Adjust CMAKE_MODULE_PATH to find FindOculusSDK.cmake or set OculusSDK_DIR
  to the directory containing a CMake configuration file for OculusSDK.  The
  file will have one of the following names:

```
OculusSDKConfig.cmake
oculussdk-config.cmake
```

I think I am not building OculusSDK properly right? Or I should cp something somewhere to make oculus_rviz_plugins find the SDK...

**Comment by fredrabelo** [comment]
@wjwwood is there any build instructions available?

**Comment by wjwwood** [comment]
Not that I'm aware of, @dgossow may know. I didn't originally write this package.

**Comment by dgossow** [comment]
It's a while ago and @tfoote set this up initially, but as far as I remember, you need the oculus_sdk in one catkin workspace since it's cmake only, and oculs_plugins in a separate workspace on top of the first one.

**Comment by fredrabelo** [comment]
Thanks for the answer @dgossow! Do we have to build rviz_plugins it with any specific flag or argument on catkin_make? or in the cmake for oculus_sdk ?

**Comment by dgossow** [comment]
It should just work, I think..

**Comment by fredinhuf** [comment]
I tried with both on my catkin_ws and as expected could not build oculus_sdk because it is not catkinized

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - oculus_sdk (plain cmake)
-- ~~  - oculus_rviz_plugins
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at /opt/ros/groovy/share/catkin/cmake/catkin_workspace.cmake:88 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.
Call Stack (most recent call first):
  CMakeLists.txt:63 (catkin_workspace)

-- Configuring incomplete, errors occurred!
Invoking "cmake" failed

---

So I tried it isolated
catkin_make_isolated --install

and everything seemed well until:
-- Installing: /etc/udev/rules.d/90-oculus-groovy.rules
CMake Error at LibOVR/cmake_install.cmake:127 (FILE):
  file INSTALL cannot copy file
  "/home/fredrabelo/catkin_ws/src/oculus_sdk/LibOVR/90-oculus-groovy.rules"
  to "/etc/udev/rules.d/90-oculus-groovy.rules".
Call Stack (most recent call first):
  cmake_install.cmake:41 (INCLUDE)

make: **\* [install] Error 1
Failed to process package 'oculus_sdk': 

## Command 'make install' returned non-zero exit status 2 

It could not copy 90-oculus-groovy.rules. I tried to put it there manually and also tried 
sudo catkin_make_isolated. No Work.

So no solution by having the oculus-sdk on my catkin workspace...

---

So I went back to trying with OculusSDK on /home/fredrabelo/OculusSDK. then: sudo make (everything went well)
then, I tried to catkin_make on my catkin workspace having oculus_rviz_plugins in several ways as I've seen somewhere:
catkin_make -OCULUS_INCLUDE_DIR="/home/fredrabelo/OculusSDK/LibOVR/Include/"

still no work :(

**Comment by dgossow** [comment]
You need to disable the INSTALL_UDEV_RULES flag.

**Comment by fredinhuf** [comment]
Yep! It worked. catkin-isolated with this flag disabled installed the plugin correctly with sdk 0.2.3. Thanks a lot @dgossow !!
'
I am trying to make it work with sdk 0.3.2 however, and I am getting error building it with the new sdk:

Linking CXX executable OculusWorldDemo
CMakeFiles/OculusWorldDemo.dir/OculusWorldDemo.cpp.o: In function `OculusWorldDemoApp::OculusWorldDemoApp()':
OculusWorldDemo.cpp:(.text+0x3bb): undefined reference to`OptionSelectionMenu::OptionSelectionMenu(OptionSelectionMenu*)'
OculusWorldDemo.cpp:(.text+0x3cd): undefined reference to `RenderProfiler::RenderProfiler()'
OculusWorldDemo.cpp:(.text+0x46e): undefined reference to`OptionSelectionMenu::~OptionSelectionMenu()'
CMakeFiles/OculusWorldDemo.dir/OculusWorldDemo.cpp.o: In function `OculusWorldDemoApp::~OculusWorldDemoApp()':
OculusWorldDemo.cpp:(.text+0x5dd): undefined reference to`CleanupDrawTextFont()'

and it goes on for a lot of functions with undefined reference. 

[...]

../../LibOVR/libovr.so: undefined reference to `OVR::SensorFactoryCalibrationImpl::SensorFactoryCalibrationImpl()'
collect2: ld returned 1 exit status
make[2]: **\* [Samples/OculusWorldDemo/OculusWorldDemo] Error 1
make[1]: **\* [Samples/OculusWorldDemo/CMakeFiles/OculusWorldDemo.dir/all] Error 2
make: **\* [all] Error 2
<== Failed to process package 'oculus_sdk': 
  Command 'make -j4 -l4' returned non-zero exit status 2

Any idea what could solves this?

**Comment by dgossow** [comment]
Where did you get the new SDK from? The linker errors suggests that maybe some files are not included in the CMakeLists.txt or so.

**Comment by fredinhuf** [comment]
Found a modified version of the SDK on github. Now trying to get the plugin to work with dk2 using this new SDK. sounds promising.
